In [2]:
import numpy as np

In [3]:
mylist=[1,2,3,4,5]

arr=np.array(mylist)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [9]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[7,8,9,10,11]

arr=np.array([my_list1,my_list2,my_list3])

In [10]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [11]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [14]:
arr[3]

4

In [15]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[7,8,9,10,11]

arr=np.array([my_list1,my_list2,my_list3])



In [16]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [17]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [20]:
arr=np.arange(0,10,step=2)

In [21]:
arr

array([0, 2, 4, 6, 8])

In [24]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [25]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[3:]=100

In [28]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [29]:
val=2
arr<val

array([ True, False, False, False, False, False, False, False, False])

In [30]:
arr*val

array([  2,   4,   6, 200, 200, 200, 200, 200, 200])

In [31]:
arr[arr<5]

array([1, 2, 3])